In [22]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
df = pd.read_csv('/content/drive/MyDrive/cleaned_toronto_dataset.csv')
df

,host_is_superhost,host_identity_verified,latitude,longitude,accommodates,bedrooms,beds,price,minimum_nights,maximum_nights,...,room_type_Shared room,distance_from_toronto,TV,Cooking basics,Kitchen,Air conditioning,Heating,Wifi,Carbon monoxide alarm,Pool
0,0.0,1.0,43.645900,-79.424230,10.0,5.0,7.0,469.0,28,730,...,0,3.400586,1,0,1,1,1,1,0,0
1,0.0,0.0,43.640800,-79.376730,2.0,1.0,1.0,101.0,180,365,...,0,1.474283,1,0,0,1,1,1,0,1
2,0.0,1.0,43.646080,-79.390320,4.0,1.0,2.0,125.0,28,1125,...,0,0.977532,1,1,1,0,1,1,1,1
3,0.0,0.0,43.690320,-79.352360,2.0,1.0,1.0,450.0,28,1125,...,0,4.817020,0,0,0,0,0,0,0,0
4,0.0,1.0,43.676390,-79.310170,1.0,1.0,1.0,37.0,30,1125,...,0,6.417401,0,1,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16408,0.0,1.0,43.648363,-79.393105,2.0,1.0,1.0,161.0,28,365,...,0,0.961771,1,1,1,1,0,1,0,0
16409,0.0,1.0,43.646810,-79.393862,2.0,1.0,1.0,161.0,28,365,...,0,1.114237,1,1,1,1,0,1,0,0
16410,1.0,1.0,43.685906,-79.400021,2.0,1.0,1.0,148.0,3,30,...,0,3.881480,1,1,1,1,0,1,1,0
16411,1.0,1.0,43.642516,-79.380507,1.0,1.6,3.0,500.0,5,365,...,0,1.208003,1,1,1,1,1,1,1,0
16412,1.0,1.0,43.662690,-79.422290,2.0,1.0,1.0,150.0,28,90,...,0,3.318008,1,0,1,1,0,1,1,0

In [24]:
# Split features and target
X = df.drop(['price'], axis=1)
y = df['price']

In [25]:
X = preprocessor.fit_transform(X)

In [26]:
# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Build neural network model
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.2),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),
    Dense(1)
])

In [27]:
# Compile model
optimizer = Adam(learning_rate=0.001)
model.compile(loss='mse', optimizer=optimizer)

# Train model
history = model.fit(X_train, y_train, validation_data=(X_val, y_val),
                    batch_size=128, epochs=100, verbose=1,
                    callbacks=[tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)])

Epoch 1/100
103/103 [==============================] - 3s 7ms/step - loss: 33808.6641 - val_loss: 34499.9336
Epoch 2/100
103/103 [==============================] - 1s 5ms/step - loss: 32275.1074 - val_loss: 33462.7344
Epoch 3/100
103/103 [==============================] - 1s 5ms/step - loss: 30447.0176 - val_loss: 32782.4531
Epoch 4/100
103/103 [==============================] - 1s 5ms/step - loss: 28242.1426 - val_loss: 30506.8535
Epoch 5/100
103/103 [==============================] - 1s 5ms/step - loss: 25839.9277 - val_loss: 27330.6250
Epoch 6/100
103/103 [==============================] - 1s 5ms/step - loss: 23423.9785 - val_loss: 24160.7109
Epoch 7/100
103/103 [==============================] - 1s 6ms/step - loss: 20996.8379 - val_loss: 21773.9707
Epoch 8/100
103/103 [==============================] - 1s 6ms/step - loss: 18681.1211 - val_loss: 20100.6895
Epoch 9/100
103/103 [==============================] - 1s 6ms/step - loss: 16652.7559 - val_loss: 16041.4844
Epoch 10/100
103/103 [==============================] - 1s 8ms/step - loss: 14740.6748 - val_loss: 15326.3311
Epoch 11/100
103/103 [==============================] - 1s 8ms/step - loss: 13066.7588 - val_loss: 13082.8545
Epoch 12/100
103/103 [==============================] - 1s 7ms/step - loss: 11575.9297 - val_loss: 12227.3564
Epoch 13/100
103/103 [==============================] - 1s 7ms/step - loss: 10234.4863 - val_loss: 9947.3340
Epoch 14/100
103/103 [==============================] - 1s 8ms/step - loss: 9035.5674 - val_loss: 8753.5000
Epoch 15/100
103/103 [==============================] - 1s 7ms/step - loss: 8139.8335 - val_loss: 8322.8789
Epoch 16/100
103/103 [==============================] - 1s 6ms/step - loss: 7381.8931 - val_loss: 7298.9150
Epoch 17/100
103/103 [==============================] - 1s 6ms/step - loss: 6779.0923 - val_loss: 6918.5195
Epoch 18/100
103/103 [==============================] - 1s 5ms/step - loss: 6264.1455 - val_loss: 6540.6855
Epoch 19/100
103/103 [==============================] - 1s 6ms/step - loss: 6017.3936 - val_loss: 6356.5664
Epoch 20/100
103/103 [==============================] - 1s 6ms/step - loss: 5841.6626 - val_loss: 6083.4536
Epoch 21/100
103/103 [==============================] - 1s 6ms/step - loss: 5697.3408 - val_loss: 6198.9526
Epoch 22/100
103/103 [==============================] - 1s 6ms/step - loss: 5610.7637 - val_loss: 5884.0386
Epoch 23/100
103/103 [==============================] - 1s 6ms/step - loss: 5419.6260 - val_loss: 5898.6885
Epoch 24/100
103/103 [==============================] - 1s 5ms/step - loss: 5524.5332 - val_loss: 5847.6357
Epoch 25/100
103/103 [==============================] - 1s 5ms/step - loss: 5468.8291 - val_loss: 5941.2471
Epoch 26/100
103/103 [==============================] - 1s 5ms/step - loss: 5468.6089 - val_loss: 5890.3442
Epoch 27/100
103/103 [==============================] - 1s 5ms/step - loss: 5501.1587 - val_loss: 5903.1479
Epoch 28/100
103/103 [==============================] - 1s 5ms/step - loss: 5373.6035 - val_loss: 5887.4727
Epoch 29/100
103/103 [==============================] - 1s 5ms/step - loss: 5347.5000 - val_loss: 5889.8945
Epoch 30/100
103/103 [==============================] - 1s 5ms/step - loss: 5332.9854 - val_loss: 5895.8721
Epoch 31/100
103/103 [==============================] - 1s 5ms/step - loss: 5317.6201 - val_loss: 5831.0625
Epoch 32/100
103/103 [==============================] - 1s 5ms/step - loss: 5270.6968 - val_loss: 5912.4585
Epoch 33/100
103/103 [==============================] - 1s 6ms/step - loss: 5285.7178 - val_loss: 5857.1865
Epoch 34/100
103/103 [==============================] - 1s 8ms/step - loss: 5228.3267 - val_loss: 5821.2539
Epoch 35/100
103/103 [==============================] - 1s 7ms/step - loss: 5311.8623 - val_loss: 5915.3481
Epoch 36/100
103/103 [==============================] - 1s 7ms/step - loss: 5230.3999 - val_loss: 5837.9277
Epoch 37/100
103/103 [==============================] - 1s 7ms/step - loss: 5227.7671 - val_loss: 5858.3218
Epoch 38/100
103/103 [==============================] - 1s 8ms/step - loss: 5154.1543 - val_loss: 5827.5591
Epoch 39/100
103/103 [==============================] - 1s 7ms/step - loss: 5179.0635 - val_loss: 5843.4614
Epoch 40/100
103/103 [==============================] - 1s 5ms/step - loss: 5139.1362 - val_loss: 5854.8853
Epoch 41/100
103/103 [==============================] - 1s 5ms/step - loss: 5108.6436 - val_loss: 5778.7627
Epoch 42/100
103/103 [==============================] - 1s 5ms/step - loss: 5191.1792 - val_loss: 5816.5830
Epoch 43/100
103/103 [==============================] - 1s 5ms/step - loss: 5038.2974 - val_loss: 5825.2959
Epoch 44/100
103/103 [==============================] - 1s 5ms/step - loss: 5047.8887 - val_loss: 5778.0869
Epoch 45/100
103/103 [==============================] - 1s 6ms/step - loss: 5085.8589 - val_loss: 5860.4468
Epoch 46/100
103/103 [==============================] - 1s 6ms/step - loss: 5088.2280 - val_loss: 5935.3560
Epoch 47/100
103/103 [==============================] - 1s 5ms/step - loss: 5060.1436 - val_loss: 5848.9219
Epoch 48/100
103/103 [==============================] - 1s 5ms/step - loss: 5125.7749 - val_loss: 5852.8828
Epoch 49/100
103/103 [==============================] - 1s 5ms/step - loss: 5066.8354 - val_loss: 5844.7051
Epoch 50/100
103/103 [==============================] - 1s 5ms/step - loss: 4933.0405 - val_loss: 5945.6265
Epoch 51/100
103/103 [==============================] - 1s 5ms/step - loss: 4963.3110 - val_loss: 5901.4121
Epoch 52/100
103/103 [==============================] - 1s 5ms/step - loss: 4959.0537 - val_loss: 5887.1714
Epoch 53/100
103/103 [==============================] - 1s 5ms/step - loss: 4877.1460 - val_loss: 5818.1851
Epoch 54/100
103/103 [==============================] - 1s 6ms/step - loss: 4965.1826 - val_loss: 5832.5723

In [28]:
# Evaluate model
loss = model.evaluate(X_val, y_val, verbose=0)
print(f'Validation loss: {loss:.4f}')

Validation loss: 5778.0879